### ISSUE TITLE
fix urdf config 

### ISSUE THREAD

**Issue by soblin** [team-tier4-FY22/sample_diff_drive_launch#1]
- `ros2 launch sample_diff_drive_description test.launch.py` fails because config/vehicle_info.param.yaml was replaced at 35fdba1 for `vehicle_info_util` ([related code](https://github.com/autowarefoundation/autoware.universe/blob/21d5453dfa2bf75716b8737fb7b58f3b45483e29/vehicle/vehicle_info_util/src/vehicle_info_util.cpp#L41-L51))
- I'll work on this in feature/fix-urdf-config

**Comment by shmpwk** [comment]
It seems we miss `vehicle_length` and `vehicle_width` and `caster_wheel_radius` in [the new yaml](https://github.com/team-tier4-FY22/sample_diff_drive_launch/blob/35fdba1296457115eb40751b4d3dce47d6bdf8e1/sample_diff_drive_description/config/vehicle_info.param.yaml).
We can just add these parameters into the yaml file,
but we have to consider the meaning of them as you mentioned in https://github.com/autowarefoundation/autoware/discussions/183.

**Comment by shmpwk** [comment]
Close by https://github.com/team-tier4-FY22/sample_diff_drive_launch/pull/2
